//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Spouse { get; set; }
        public string Mobile_Phone { get; set; }
        public string Home_Phone { get; set; }
        public string Home_Street { get; set; }
        public string Home_City { get; set; }
        public string Home_Postal_Code { get; set; }
        public string Home_State { get; set; }
        public string Home_Country { get; set; }
        public string Nickname { get; set; }
        public string Notes { get; set; }
    }
}
