//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MountainSummitLog
    {
        public int id { get; set; }
        public int MountainID { get; set; }
        public Nullable<System.DateTime> SummitDate { get; set; }
        public string SummitNote { get; set; }
    
        public virtual Mountain Mountain { get; set; }
    }
}
