//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WalterEntities : DbContext
    {
        public WalterEntities()
            : base("name=WalterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Mountain> Mountains { get; set; }
        public virtual DbSet<MountainSummitLog> MountainSummitLogs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Band> Bands { get; set; }
        public virtual DbSet<ACDC> ACDCs { get; set; }
    
        public virtual ObjectResult<AllClimbs_Result> AllClimbs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllClimbs_Result>("AllClimbs");
        }
    }
}
