//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalterEntities : DbContext
    {
        public WalterEntities()
            : base("name=WalterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mountain> Mountains { get; set; }
        public virtual DbSet<MountainSummitLog> MountainSummitLogs { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
    }
}
