USE [master]
GO



CREATE LOGIN [WebUser] WITH PASSWORD=N'WebUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER LOGIN [WebUser] enable--DISABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [WebUser]
GO


--sa

CREATE LOGIN [sa] WITH PASSWORD=N'sa', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

ALTER LOGIN [sa] DISABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [sa]
GO


